version: 2
updates:
  # update Python dependencies using uv
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
    # group minor/patch updates together
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  # keep Github Action versions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
